### ISSUE TITLE
Update github-pages dependency to work with latest Ruby (2.5.1)

### ISSUE THREAD

**Issue by RaevLogic** [nodegit/nodegit.github.com#57]
After cloning the nodegit.github.io repo onto my system, I kept getting this error when running `script/bootstrap` ||
```
$ script/bootstrap
Successfully installed bundler-1.16.5
Parsing documentation for bundler-1.16.5
Done installing documentation for bundler after 3 seconds
1 gem installed
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using RedCloth 4.2.9
Using i18n 0.7.0
Fetching json 1.8.2
Installing json 1.8.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/json-1.8.2/ext/json/ext/generator
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180923-15396-s6e9th.rb extconf.rb
creating Makefile

current directory:
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/json-1.8.2/ext/json/ext/generator
make "DESTDIR=" clean

current directory:
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/json-1.8.2/ext/json/ext/generator
make "DESTDIR="
generating generator-x64-mingw32.def
compiling generator.c
generator.c: In function 'generate_json':
generator.c:867:25: error: 'rb_cFixnum' undeclared (first use in this function);
did you mean 'mFixnum'?
     } else if (klass == rb_cFixnum) {
                         ^~~~~~~~~~
                         mFixnum
generator.c:867:25: note: each undeclared identifier is reported only once for
each function it appears in
generator.c:869:25: error: 'rb_cBignum' undeclared (first use in this function);
did you mean 'mBignum'?
     } else if (klass == rb_cBignum) {
                         ^~~~~~~~~~
                         mBignum
make: *** [Makefile:242: generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/json-1.8.2 for inspection.
Results logged to
C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/json-1.8.2/gem_make.out

An error occurred while installing json (1.8.2), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  github-pages was resolved to 33, which depends on
    jekyll-mentions was resolved to 0.2.1, which depends on
      html-pipeline was resolved to 1.9.0, which depends on
        activesupport was resolved to 4.2.0, which depends on
          json
```
To fix, I had to `bundle update github-pages`. Looking through the difs for `Gemfile.lock`, the dependencies `redcarpet` and `pygments` are deleted. So moving to `script/server` command, I get errors because I'm missing those two dependencies. To fix those errors, I went to the `_config.yml` and changed it to `markdown: kramdown` and `highlighter: rouge`. The command `script/server` now works and the site is generated. I was curious if you'd like me to submit a PR for these dependency updates.
![dependency issue config change](https://user-images.githubusercontent.com/38801291/46036470-6114c000-c0ba-11e8-9745-664245f2e485.png)
